title: tetretalk
email: support@tetretalk.gq
description: Play Millions of games created from users just like you! Different games for different ages! Come check out the site and consider joining our discord to know when a game is updated or when we are adding something!
baseurl: "/" 
url: "" 
google_analytics: "UA-124327558-1"

username: Tetretalk
user_description: Tetretalk
disqus_username: disqus_username


markdown: kramdown
highlighter: rouge
permalink: /:title/

gems:
  - jemoji

# For external links add external: true
links:
  - title: Home
    url: /
  - title: Community Homepage
    url: 
    external: true
  - title: Tetretalk Beta
    url: /beta/
  - title: Rules
    url: /rules/
  - title: Discord
    url: https://discordapp.com/invite/bNyeJZM
    external: true
  - title: Jobs
    url: /jobs/
  - title: Sponsors
    url: /sponsors/
  - title: Create
    url: /create/
  - title: TetreTime Live
    url: /live/
    
# Node/;FireClient(node.package.games) #
exclude: ['package.json', 'src', 'node_modules']
